### PR TITLE
Feature/update angular v16

### PR DESCRIPTION
**Pull request by srdejo**

### CODE REVIEW

**Comment by srdejo** [comment]
Update angular to v16

**Comment by grigoreme** [comment]
Bumping,  great to have that. For the time being i have copy-pasted your library to my project.
Was expected to have lots of issues but worked out of the box with latest version @16.1.0

**Review by grigoreme — COMMENTED** [review]
Just curious, why would you rename it?
Just wondering, same name but just a new major version would be enough as for me.

**Comment by srdejo** [comment]
@grigoreme  I change the name to be able to publish it in npm.js -> https://www.npmjs.com/package/angular-responsive-carousel-ng16

**Pull request closed without merging**
